run_hotspot=False#Hotspot Mode: 'True' for continouus operation, 'False' to turn off after 10 Minutes#device
heating=False#Enable heating?#device
sample_spot_diameter=0.5#Set the Diameter of the sample spot size in cm#device
sample_time=300 #Time in seconds between two samples.#session
filter_scattering_factor = 1.39 #Scattering of Filter. 1.39 for magee ae33, 1.66 for pallflex t60a20 in aethlabs maeth51#device
device_specific_correction_factor = 1 #Device specific correction factor#device
airflow_per_minute=0.07#Adjust airflow per minute in liter#session
airflow_sensor=False#Set to true if you have an airflow sensor#device
af_sensor_type=0#Currently Omron D6F are supported. (set to 0 for P0001A1 and 1 for P0010A2)#device
reverse_dutycycle=True#True for PWM pumps, False for most generic without controller!#device
pump_dutycycle=170#Power 0-255 for the pump. Set automatically if airflow sensor.#device
pwm_freq=20000#Pulse width modulation frequency for pump duty cycle. #device
swap_channels =False#Swap data channels if you see continous negative values or on Rev 2 bcMeters. #device
led_brightness=100#change LED brightness if necessary#device
compair_upload =False#Upload Data to CompAIR. Needs coordinates. #session
get_location =False#Get rough location by IP? False: Need to enter Manually below.#session
location=[00.0000,00.0000]#Location of the bcMeter. Keep syntax exactly like that [lat,lon] and keep above value to False#session
use_display=False#Set to true if your bcMeter is provided with a display#device
enable_wifi=True#Disable for use with LAN.#device
is_ebcMeter=False#set to True if you use the device for emission measurement#device
send_log_by_mail=False#Do you want to receive the log files by mail?#session
mail_logs_to='your@email.address'#Enter e-mail adress(es) to send the log files to, comma separated#session
filter_status_mail=False#Do you want to rececive a mail when filter change is suggested?#session
disable_pump_control=False#Set to True if you do not want to use the internal pump control#device
mail_sending_interval=24#Send logs every X hours (between 6 and 24)#session
email_service_password='email_service_password'#this is the password if you want to receive emails. contact jd@bcmeter.org if you want to use the service#device